# Shell variables
# Generated by 'wal'
wallpaper='/home/eyad/.config/wall.png'

# Special
background='#120d15'
foreground='#d1ccd0'
cursor='#d1ccd0'

# Colors
color0='#120d15'
color1='#965E34'
color2='#9B6768'
color3='#B48970'
color4='#6F6E94'
color5='#986D8C'
color6='#A4919D'
color7='#d1ccd0'
color8='#928e91'
color9='#965E34'
color10='#9B6768'
color11='#B48970'
color12='#6F6E94'
color13='#986D8C'
color14='#A4919D'
color15='#d1ccd0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
