--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/eyad/.config/wall.png"

-- Special
background="#120d15"
foreground="#d1ccd0"
cursor="#d1ccd0"

-- Colors
color0="#120d15"
color1="#965E34"
color2="#9B6768"
color3="#B48970"
color4="#6F6E94"
color5="#986D8C"
color6="#A4919D"
color7="#d1ccd0"
color8="#928e91"
color9="#965E34"
color10="#9B6768"
color11="#B48970"
color12="#6F6E94"
color13="#986D8C"
color14="#A4919D"
color15="#d1ccd0"
