#!/bin/bash
arxiv_post=$1
echo ""
echo ""
echo ""
echo "Path of output directory? Default = (~/arxiv)"
read outdir
if [ -z "$outdir" ]; then
    outdir=~/arxiv
fi
mkdir -p $outdir
wget "$arxiv_post" -O $outdir/tmp_file
echo "Saving tmp file"
pdf_url=$(cat $outdir/tmp_file | grep "pdf_url" | cut -d "=" -f3 | cut -d '"' -f2)
echo "Saving arxiv pdf to $outdir"
DATE=$(date +%Y_%m_%d)
echo ""
echo ""
echo ""
echo "Name of file? (Excluding '.pdf')"
read varname
wget "$pdf_url" -O $outdir/"$DATE"-"$varname".pdf
rm $outdir/tmp_file
echo "Removed tmp file and finished!"
if [ $outdir == '~/arxiv' ]; then
    rclone copy $outdir harvard-rclone:arxiv
fi
zathura $outdir/"$DATE"-"$varname".pdf
