#!/bin/bash

# menu_fun='dmenu'
menu_fun='rofi -dmenu -theme sidebar'
menu=('2D x**2' '3D x**2-y**2' '2D Parametric t,t' '3D Parametric u,v,u*v' '3d Contour x**2+y**2')
echo "${menu[0]}"
mode=$(printf '%s\n' "${menu[@]}"|sed 's/^ //'|$menu_fun -b -sb seagreen -i -p "Type")
case $mode in
    "${menu[0]}")
        functions=('x**2' 'sin(x)' 'sin(x)/x')
        plotFun=$(printf '%s\n' "${functions[@]}"|sed 's/^ //'| $menu_fun -b -sb seagreen -i -p "Function:")
        gnuplot -e "plot $plotFun;pause mouse close"
        ;;
    "${menu[1]}")
        functions=('x**2+y**2' 'sin(sqrt(x**2+y**2))/sqrt(x**2+y**2)')
        plotFun=$(printf '%s\n' "${functions[@]}"|sed 's/^ //'| $menu_fun -b -sb seagreen -i -p "Function:")
        gnuplot -e "set contour;set cntrparam levels 15;set isosamples 40;splot $plotFun;pause mouse close"
        ;;
    "${menu[2]}")
        functions=('t,t')
        plotFun=$(printf '%s\n' "${functions[@]}"|sed 's/^ //'| $menu_fun -b -sb seagreen -i -p "Function:")
        gnuplot  -e "set parametric;set trange [0:2*pi];plot ${plotFun};pause mouse close"
        ;;
    "${menu[3]}")
        functions=('t,t')
        plotFun=$(printf '%s\n' "${functions[@]}"|sed 's/^ //'| $menu_fun -b -sb seagreen -i -p "Function:")
        gnuplot  -e "sset isosamples 40;et parametric;set trange [0:2*pi];set urange [0:pi];splot ${plotFun} ;pause mouse close"
        ;;
    "${menu[4]}")
        functions=('x**2+y**2' 'sin(x)*cos(y)' 'sin(sqrt(x**2+y**2))/sqrt(x**2+y**2)')
        plotFun=$(printf '%s\n' "${functions[@]}"|sed 's/^ //'| $menu_fun -b -sb seagreen -i -p "Function:")
        gnuplot  -e "set isosamples 40;set contour;set cntrparam levels 15; unset surface;set view map;splot ${plotFun} ;pause mouse close"
        ;;
esac
