#!/usr/bin/env bash

set -euo pipefail
case "$(uname -s)" in
  Linux)
    sudo nixos-rebuild switch --flake .#"$@"
    ;;
  Darwin)
    darwin-rebuild switch --flake ".#$(hostname -s)" "$@"
    ;;
  *)
    echo "I don't know how to build on a $(uname -s) system."
    exit 1
    ;;
esac
