#!/usr/bin/env bash

set -euo pipefail
case "$(uname -s)" in
  Linux)
    sudo nixos-rebuild --flake . "$@"
    ;;
  Darwin)
    nix --experimental-features 'nix-command flakes' build ".#darwinConfigurations.$(hostname -s).system"

    # darwin-rebuild --flake ".#$(hostname -s)" "$@"
    ./result/sw/bin/darwin-rebuild activate --flake ".#$(hostname -s)" "$@"
    ;;
  *)
    echo "I don't know how to build on a $(uname -s) system."
    exit 1
    ;;
esac
