name: semla

# Specify the conda channels that you wish to grab packages from, in order of priority.
channels:
- defaults
- conda-forge
- glemaitre
- maciejkula
- ioam
- defaults
- pkgw-forge
- datamicroscopes
- distributions

# Specify the packages that you would like to install inside your environment. Version numbers are allowed, and conda will automatically use its dependency solver to ensure that all packages work with one another.
dependencies:
- python=3.10
- pandas
