#!/bin/sh

# In LARBS, ~/.config/wall.png is the location of the system wallpaper.  This
# script, if given an argument, moves it there.  This script without an
# argument sets ~/.config/wall.png as the wallpaper, which is required on login
# if you don't want a black screen.

[ ! -z "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed."

# If pywal is installed, use it.
type wal >/dev/null 2>&1 && {
    wpg -d wall.png >/dev/null 2>&1;
    rm -rf ~/.config/wpg/schemes/
    wpg -n -s ~/.config/wall.png --backend "$2" && \
    wal -c && \
	wal --backend "$2" -s -i ~/.config/wall.png -o ~/.config/wal/postrun && \
	cat ~/.cache/wal/sequences && \
	xsetroot -name "fsignal:xrdb";
	i3-msg restart;
	# spicetify apply;
	killall spotify;
	}
	#setsid dwmblocks >/dev/null 2>&1 & }

#xwallpaper --zoom ~/.config/wall.png
#nitrogen --set-zoom ~/.config/wall.png
